### ISSUE TITLE
 返回错误...{u'retcode': 100001, u'errmsg': u'error!!!'}

### ISSUE THREAD

**Issue by Jax-EC** [Yinzo/SmartQQBot#105]
返回错误...{u'retcode': 100001, u'errmsg': u'error!!!'}

错误信息:
[INFO] Thu, 02 Feb 2017 08:58:07  bot.py line 143: Try cookie login...
[ERROR] Thu, 02 Feb 2017 08:58:07  bot.py line 311: <class 'smart_qq_bot.bot.CookieLoginFailed'>
Traceback (most recent call last):
  File "/root/SmartQQBot/src/smart_qq_bot/bot.py", line 309, in login
    self._login_by_cookie()
  File "/root/SmartQQBot/src/smart_qq_bot/bot.py", line 173, in _login_by_cookie
    raise CookieLoginFailed("Login step 1 failed with response:\n %s " % ret)
CookieLoginFailed: Login step 1 failed with response:
 {u'retcode': 100001, u'errmsg': u'error!!!'} 
[INFO] Thu, 02 Feb 2017 08:58:07  bot.py line 197: RUNTIMELOG Trying to login by qrcode.
[INFO] Thu, 02 Feb 2017 08:58:07  bot.py line 198: RUNTIMELOG Requesting the qrcode login pages...
[INFO] Thu, 02 Feb 2017 08:58:07  bot.py line 246: Downloading QRCode file...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/SmartQQBot/src/smart_qq_bot/bot.py", line 63, in show_qr
    root = Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1818, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
TclError: no display name and no $DISPLAY environment variable

^C[INFO] Thu, 02 Feb 2017 08:58:16  run.py line 14: User stop. exit.

**Comment by Jax-EC** [comment]
问题解决了...在没有gui的情况下 会出现这种错误...看了 操作指南 发现的...
建议 出现这个错误的时候 显示一些 提示性的信息。
