### ISSUE TITLE
 No JSON object could be decoded

### ISSUE THREAD

**Issue by billyyong** [Yinzo/SmartQQBot#111]
Traceback (most recent call last):
  File "run.py", line 12, in <module>
    run()
  File "C:\Users\Administrator\Desktop\SmartQQBot-master\SmartQQBot-master\src\s
mart_qq_bot\main.py", line 108, in run
    main_loop(**vars(args))
  File "C:\Users\Administrator\Desktop\SmartQQBot-master\SmartQQBot-master\src\s
mart_qq_bot\main.py", line 55, in main_loop
    bot.login(no_gui)
  File "C:\Users\Administrator\Desktop\SmartQQBot-master\SmartQQBot-master\src\s
mart_qq_bot\bot.py", line 328, in login
    self.get_group_list_with_group_id()
  File "C:\Users\Administrator\Desktop\SmartQQBot-master\SmartQQBot-master\src\s
mart_qq_bot\bot.py", line 639, in get_group_list_with_group_id
    rsp_json = json.loads(response)
  File "C:\Python27\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by Yinzo** [comment]
现在这个函数失败会自动重试了，如果多次失败，网络环境可能有问题

**Comment by billyyong** [comment]
谢谢，Yinzo.
