### ISSUE TITLE
连接qun.qq.com超时

### ISSUE THREAD

**Issue by james0479** [Yinzo/SmartQQBot#114]
无论怎么退出重新登录，甚至换qq号也不行，启动就报错

INFO] Thu, 06 Apr 2017 15:15:27  main.py line 51: Initializing...
[INFO] Thu, 06 Apr 2017 15:15:27  plugin.py line 100: Plugin [basic] loaded.
[INFO] Thu, 06 Apr 2017 15:15:27  plugin.py line 100: Plugin [manager] loaded.
[INFO] Thu, 06 Apr 2017 15:15:27  plugin.py line 100: Plugin [weather] loaded.
[INFO] Thu, 06 Apr 2017 15:15:27  bot.py line 143: Try cookie login...
[WARNING] Thu, 06 Apr 2017 15:15:27  http_client.py line 55: Failed to load cookie file cookie/cookie.data
[ERROR] Thu, 06 Apr 2017 15:15:27  bot.py line 320: <class 'smart_qq_bot.bot.CookieLoginFailed'>
Traceback (most recent call last):
  File "/map/app/SmartQQBot/src/smart_qq_bot/bot.py", line 318, in login
    self._login_by_cookie()
  File "/map/app/SmartQQBot/src/smart_qq_bot/bot.py", line 173, in _login_by_cookie
    raise CookieLoginFailed("Login step 1 failed with response:\n %s " % ret)
CookieLoginFailed: Login step 1 failed with response:
 {u'retcode': 100001, u'errmsg': u'error!!!'} 
[INFO] Thu, 06 Apr 2017 15:15:27  bot.py line 197: RUNTIMELOG Trying to login by qrcode.
[INFO] Thu, 06 Apr 2017 15:15:27  bot.py line 198: RUNTIMELOG Requesting the qrcode login pages...
[INFO] Thu, 06 Apr 2017 15:15:27  bot.py line 247: Downloading QRCode file...
[INFO] Thu, 06 Apr 2017 15:15:56  bot.py line 143: Try cookie login...
[INFO] Thu, 06 Apr 2017 15:15:56  bot.py line 193: Login by cookie succeed. account: 3129646606
[INFO] Thu, 06 Apr 2017 15:15:56  bot.py line 461: RUNTIMELOG Requesting the online buddies.
Traceback (most recent call last):
  File "run.py", line 12, in <module>
    run()
  File "/map/app/SmartQQBot/src/smart_qq_bot/main.py", line 108, in run
    main_loop(**vars(args))
  File "/map/app/SmartQQBot/src/smart_qq_bot/main.py", line 55, in main_loop
    bot.login(no_gui)
  File "/map/app/SmartQQBot/src/smart_qq_bot/bot.py", line 328, in login
    self.get_group_list_with_group_id()
  File "/map/app/SmartQQBot/src/smart_qq_bot/bot.py", line 639, in get_group_list_with_group_id
    response = self.client.post(url, data=data, refer='http://qun.qq.com/member.html')
  File "/map/app/SmartQQBot/src/smart_qq_bot/http_client.py", line 88, in post
    verify=SSL_VERIFY,
  File "/usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='qun.qq.com', port=80): Max retries exceeded with url: /cgi-bin/qun_mgr/get_group_list (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f7ca44c5e50>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by Yinzo** [comment]
你所在的网络环境连接 qun.qq.com 有问题，我已经 push 了一个处理这个异常的 commit 了，现在不会导致抛出异常了。

但是你与这个请求相关的api仍然无法使用。我这边不存在这个连接问题。
