### ISSUE TITLE
I meet  an error...Please help me,Thanks

### ISSUE THREAD

**Issue by boxlab** [Yinzo/SmartQQBot#134]
This is Error Message:
---------------------------------------------
[INFO] Fri, 07 Jul 2017 15:08:55  bot.py line 188: Try cookie login...
Traceback (most recent call last):
  File "run.py", line 12, in <module>
    run()
  File "/home/pi/Desktop/SmartQQBot/src/smart_qq_bot/main.py", line 112, in run
    main_loop(**vars(args))
  File "/home/pi/Desktop/SmartQQBot/src/smart_qq_bot/main.py", line 56, in main_loop
    bot.login(no_gui)
  File "/home/pi/Desktop/SmartQQBot/src/smart_qq_bot/bot.py", line 368, in login
    if self._login_by_cookie():
  File "/home/pi/Desktop/SmartQQBot/src/smart_qq_bot/bot.py", line 228, in _login_by_cookie
    ret2 = json.loads(response2)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
--------------------------------------------------------------------------
Please give me some advices.Thank you very much!

**Comment by winkidney** [comment]
0. 你的启动参数是啥？环境是啥？
1. 后续有日志吗？
2. 有二维码图片弹出吗？
3. 包目录下有出现二维码图片吗？
4. 尝试过扫码吗？

这是cookie登录失败了，通常来说不用管。需要提供进一步信息才知道你的问题。

**Comment by boxlab** [comment]
0.python run.py
1.不明
2.没有
3.有
4.有；并且这一堆错误就是在扫码之后出现的，当我再次运行时使用cookie登录，再次爆出这些错误

**Comment by boxlab** [comment]
补充：
0.启动命令：python run.py
环境：Debian Python 2.7.9
  备注：以前都能用的

**Comment by winkidney** [comment]
谢谢你的 信息，有时间的时候来看看：）



2017-07-07 17:09 GMT+08:00 BOX-Lab <notifications@github.com>:

**Comment by Yinzo** [comment]
这个问题根据群里的反馈似乎是腾讯服务器的抽风问题，现在我这边测试似乎是没问题的 :)
