### ISSUE TITLE
无法接受临时聊天群的信息？

### ISSUE THREAD

**Issue by MofeLee** [Yinzo/SmartQQBot#75]
拉入群中一收到消息就出现这个错误
```
[ERROR] Thu, 21 Jul 2016 20:25:01  main.py line 59: Exception occurs when checking msg.
Traceback (most recent call last):
  File "/Users/Mofe/_git/SmartQQBot/src/smart_qq_bot/main.py", line 52, in main_loop
    [mk_msg(msg) for msg in msg_list]
  File "/Users/Mofe/_git/SmartQQBot/src/smart_qq_bot/messages.py", line 103, in mk_msg
    return MSG_TYPE_MAP[msg_dict['poll_type']](msg_dict)
KeyError: u'discu_message'
```

**Comment by Yinzo** [comment]
对的，暂时还不支持讨论组的

**Comment by zhongjingjogy** [comment]
可以打个补丁来避免这个报错,这个要修改bot.py这个文件
```
# line at the beginning
DISCU_MSG = "discu_message"

# line closed to the end
class DiscuMsg(QMessage):

    def __init__(self, msg_dict):
        super(DiscuMsg, self).__init__(msg_dict)

# register to the MSG_TYPE_MAP
MSG_TYPE_MAP = {
    GROUP_MSG: GroupMsg,
    INPUT_NOTIFY_MSG: QMessage,
    KICK_MSG: QMessage,
    SESS_MSG: SessMsg,
    PRIVATE_MSG: PrivateMsg,
    DISCU_MSG: DiscuMsg
}
```

**Comment by MofeLee** [comment]
嗯，好的，谢啦
