### ISSUE TITLE
插件全部没起作用

### ISSUE THREAD

**Issue by moboard** [Yinzo/SmartQQBot#92]
` python run.py`
```
[INFO] Thu, 06 Oct 2016 14:37:11  main.py line 51: Initializing...
[INFO] Thu, 06 Oct 2016 14:37:11  plugin.py line 94: Plugin [basic] loaded.
[INFO] Thu, 06 Oct 2016 14:37:12  plugin.py line 94: Plugin [manager] loaded.
[INFO] Thu, 06 Oct 2016 14:37:12  plugin.py line 94: Plugin [satoru] loaded.
[INFO] Thu, 06 Oct 2016 14:37:12  bot.py line 140: Try cookie login...
[ERROR] Thu, 06 Oct 2016 14:37:15  bot.py line 302: <class 'smart_qq_bot.bot.CookieLoginFailed'>
Traceback (most recent call last):
  File "/home/my/tmp/SmartQQBot-master/src/smart_qq_bot/bot.py", line 300, in login
    self._login_by_cookie()
  File "/home/my/tmp/SmartQQBot-master/src/smart_qq_bot/bot.py", line 164, in _login_by_cookie
    raise CookieLoginFailed("Login step 1 failed with response:\n %s " % ret)
smart_qq_bot.bot.CookieLoginFailed: Login step 1 failed with response:
 {'errmsg': 'error!!!', 'retcode': 100012} 
[INFO] Thu, 06 Oct 2016 14:37:15  bot.py line 188: RUNTIMELOG Trying to login by qrcode.
[INFO] Thu, 06 Oct 2016 14:37:15  bot.py line 189: RUNTIMELOG Requesting the qrcode login pages...
[INFO] Thu, 06 Oct 2016 14:37:15  bot.py line 237: Downloading QRCode file...
[INFO] Thu, 06 Oct 2016 14:37:32  bot.py line 140: Try cookie login...
[INFO] Thu, 06 Oct 2016 14:37:32  bot.py line 184: Login by cookie succeed. account: 765106786
[INFO] Thu, 06 Oct 2016 14:37:32  bot.py line 438: RUNTIMELOG Requesting the online buddies.
[INFO] Thu, 06 Oct 2016 14:37:32  bot.py line 564: RUNTIMELOG Requesting the group list.
[INFO] Thu, 06 Oct 2016 14:37:33  bot.py line 315: User information got: user name is [分析师]
[INFO] Thu, 06 Oct 2016 14:37:33  bot.py line 324: RUNTIMELOG QQ：765106786 login successfully, Username：分析师
[INFO] Thu, 06 Oct 2016 14:37:33  manager.py line 49: Plugin Manager is available now:)
[INFO] Thu, 06 Oct 2016 14:39:09  satoru.py line 61: Satoru's data file saved.
^C[INFO] Thu, 06 Oct 2016 14:39:46  run.py line 14: User stop. exit.

```

登陆上了，但是插件不起作用。

**Comment by winkidney** [comment]
怎么判断没起作用的呢？
```
[INFO] Thu, 06 Oct 2016 14:37:11  plugin.py line 94: Plugin [basic] loaded.
[INFO] Thu, 06 Oct 2016 14:37:12  plugin.py line 94: Plugin [manager] loaded.
[INFO] Thu, 06 Oct 2016 14:37:12  plugin.py line 94: Plugin [satoru] loaded.
```

**Comment by Yinzo** [comment]
请对照readme确认使用方法是否正确
